apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: andreas-aman
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:14
        env:
        - name: POSTGRES_PASSWORD
          value: "supersecret"
      serviceAccountName: curity2
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: curity2
  namespace: andreas-aman
